name: Deploy admin-api to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy admin-api to EC2
    runs-on: ubuntu-latest
    environment: admin-stagging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Skip if not original repo
        if: github.repository != 'dev-tanuja/admin-api'
        run: |
          echo "This is a fork. Skipping deployment."
          exit 0

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd admin-api
            git pull origin main
            npm install
            pm2 restart admin-api
